### ISSUE TITLE
TemplateSyntaxError appeared after downloading 1.3.3.

### ISSUE THREAD

**Issue by MaximeVlnve** [assem-ch/django-jet-reboot#65]
Hi ! 

As the title explains, I have a `TemplateSyntaxError` in my project. When I force my project to use the `1.3.2` version, this error does not happen anymore. 
![image](https://user-images.githubusercontent.com/34546974/204316067-ce943984-7cca-48c0-8723-4c93d5cedc1d.png)

Does someone have any idea about that ? 

Thanks in advance !

**Comment by mer-sublime** [comment]
The `blocktranslate` template tag used here appeared in Django 3.1 ([doc](https://docs.djangoproject.com/fr/3.1/topics/i18n/translation/#blocktranslate-template-tag)). It was called `blocktrans` in the version you're using ([3.0.9](https://docs.djangoproject.com/fr/3.0/topics/i18n/translation/#blocktrans-template-tag)).

Because of this it seems `django-jet-reboot` now requires Django > 3.1 instead of 3.0 but I see no mention of this in the Changelog or the pypi's page.

**Comment by assem-ch** [comment]
As @mer-sublime  suggested, it is better to update django to 3.1 , we'll release the fix but it may take time
